config/routes.rb
Rails.application.routes.draw do
  resources :campaigns

  root "campaigns#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  validates :position, uniqueness: { allow_blank: true }
  after_save :set_position

  enum :state, { draft: 0, published: 1, archived: 2 }

  private

  def set_position
    return if state == :draft
    return unless saved_change_to_published_at?

    CampaignPositionService.new.insert_and_sort(campaign: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: %i[ show edit update destroy ]

  # GET /campaigns or /campaigns.json
  def index
    @campaigns = sorted_campaigns
  end

  # GET /campaigns/1 or /campaigns/1.json
  def show; end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns or /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to campaign_url(@campaign), notice: "Campaign was successfully created." }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1 or /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to campaign_url(@campaign), notice: "Campaign was successfully updated." }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1 or /campaigns/1.json
  def destroy
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: "Campaign was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def sorted_campaigns
    # Probably want to build a Query class instead
    campaigns = Campaign.all.select(:id, :title, :state).order(:position).group_by{ |c| c.state }
    display_order = ['published', 'draft', 'archived']
    campaigns.sort_by { |elem| display_order.index(elem.first) }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def campaign_params
    params.require(:campaign).permit(:title, :description, :state, :published_at, :position)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper

  def campaign_state_colour(state:)
    state_colour_classes = {
      draft: 'text-orange-500',
      published: 'text-green-500',
      archived: 'text-slate-500'
    }

    state_colour_classes[state.to_sym] || 'text-gray-500'
  end

  def published_at_formatted(time:)
    return 'Unpublished' if !time

    time.strftime("#{time.day.ordinalize} %B %Y at %I:%M%p")
  end
end

app/views/campaigns/_campaign.html.erb
<div id="<%= dom_id campaign %>">
  <p>
    <strong>Title:</strong>
    <%= campaign.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= campaign.description %>
  </p>

  <p>
    <strong>State:</strong>
    <%= campaign.state %>
  </p>

  <p>
    <strong>Published at:</strong>
    <%= campaign.published_at %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= campaign.position %>
  </p>

</div>

app/views/campaigns/_campaign_group.html.erb
<% campaigns.each do |campaign| %>
    <tr class="border-t border-gray-300 hover:bg-gray-100">
        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= campaign.title %></td>
        <td class="whitespace-nowrap px-3 py-4 text-sm <%= campaign_state_colour(state: campaign.state) %>"><%= campaign.state.humanize %></td>
        <td class="relative whitespace-nowrap text-indigo-500 py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-3">
            <%= link_to "View", campaign_path(campaign), data: { turbo_frame: "modal", action: 'click->modal#open'} %>
        </td>
    </tr>
<% end %>

app/views/campaigns/_campaign_modal.html.erb
<%= render TurboModal.new(title: "Campaign") do %>
  <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
    <div class="order-1">
      <h1 class="pb-1 font-semibold border-gray-300 border-b">Title</h1>
      <h2 class="pt-1"><%= @campaign.title %></h2>
    </div>
    <div class="order-3 md:order-2">
      <h1 class="pb-1 font-semibold border-gray-300 border-b">Current state</h1>
      <h2 class="<%= campaign_state_colour(state: @campaign.state) %> pt-1"><%= @campaign.state.humanize %></h2>
    </div>

    <div class="order-2 md:order-3">
      <h1 class="pb-1 font-semibold border-gray-300 border-b">Description</h1>
      <p class="pt-1"><%= @campaign.description %></p>
    </div>

    <div class="order-4">
      <h1 class="pb-1 font-semibold border-gray-300 border-b">Published at</h1>
      <p class="pt-1"><%= published_at_formatted(time: @campaign.published_at)%></p>
    </div>
  </div>
<% end %>

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign) do |form| %>
  <% if campaign.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
        <% campaign.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.number_field :state %>
  </div>

  <div>
    <%= form.label :published_at, style: "display: block" %>
    <%= form.datetime_field :published_at %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Show this campaign", @campaign %> |
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-bold">Campaigns</h1>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full">
          <thead class="bg-white">
            <tr class="text-gray-900">
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left font-semibold text-gray-900 sm:pl-3">Title</th>
              <th scope="col" class="px-3 py-3.5 text-left font-semibold text-gray-900">State</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-3">
                <span class="sr-only">Show</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white">
            <% @campaigns.each do |status, campaigns| %>
              <tr class="border-t border-gray-200">
                <th colspan="5" scope="colgroup" class="bg-gray-50 py-2 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-3"><%= status.humanize %></th>
              </tr>
              <%= render 'campaign_group', campaigns: campaigns %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/new.html.erb
<h1>New campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/show.html.erb
<%= render 'campaign_modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Go Certify Tech Task</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <main class="container mx-auto py-10">
       <div class="relative" data-controller="modal">
        <div
        data-action="click->modal#hide"
        data-modal-target="modalBackground">
        </div>
        <%= turbo_frame_tag "modal" %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>